### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by trasher** [Aohzan/ecodevices#1]
Hello,

First of all, thank you for this integration! :+1: 

I've noticed you did not specify a license; could you consider adding one?

On github, this is quite simple, just add a new file named "LICENSE" at the root of the project; a button "choose a license template" will appear.

I take a look on my instance: home assistant is under an apache license, several integrations are MIT (hacs, smartir, anniversaries, ...), at least one is GPL (localtuya).

Of course, feel free to choose the one you prefer :)

Best regards

**Comment by Aohzan** [comment]
Hello,

Thank you ;) I did it for my python package but not for my home assistant integrations :/, fixed now
