### ISSUE TITLE
cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor'

### ISSUE THREAD

**Issue by sylarevan** [Aohzan/ecodevices#10]
Hi there, and thank you for this nice integration.

Since 2.3.0 which should bring compatibility to the new energy management system in 2021.8, I now get an error when HA starts:
` Unable to prepare setup for platform ecodevices.sensor: Platform not found (cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)). `

I have tried to remove and readd the integration with no success: my two sensors (a Linky on Teleinfo 1 and a gas counter)  do not show anymore.

Rolling back to 2.2.0 solves the issue.

I'm using HA v.2018.8.8.

**Comment by Aohzan** [comment]
Hello
My bad, the new STATE_CLASS_TOTAL_INCREASING will be only on the next release (202109), please stay on 2.2.0 until then
I'll add a mention in changelog
Thank you :slightly_smiling_face:

**Comment by sylarevan** [comment]
Wow, "solved" in 2 minutes! Thanks.
