### ISSUE TITLE
Compatibility with HP/HC not available ?

### ISSUE THREAD

**Issue by Mikael2588** [Aohzan/ecodevices#14]
Hello @Aohzan and thank for you work!

I have an EDF contract with HP/HC so in the Teleinfo frame the field “T1_base” is always set at 0.
My real consumption is in the fields “T1_HCHC” and “T1_HCHP”.
It is possible to catch those fields in HA ?

Thanks in advance.

**Comment by Aohzan** [comment]
Hello,
you have them in the attributes of main sensor : https://github.com/Aohzan/ecodevices/blob/master/custom_components/ecodevices/sensor.py#L227

**Comment by Mikael2588** [comment]
Hello,
Thanks for the quick answer  !
