### ISSUE TITLE
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'

### ISSUE THREAD

**Issue by edelans** [Aohzan/ecodevices#15]
Hello 👋 , 

I just updated to v3.0 from 2.4 (with HACS). 

I get this error after restarting HA : 

<img width="852" alt="CleanShot 2021-11-07 at 22 53 31@2x" src="https://user-images.githubusercontent.com/2805640/140663215-1c0cf8d8-edca-46d7-b94f-1f2a3ef65521.png">

Is it related to the "Add device configuration link" from the changelog ?

**Comment by Aohzan** [comment]
Hello,
Yes, you must have the last Home Assistant version : 2021.11, can you upgrade ?

**Comment by edelans** [comment]
@Aohzan yep, I was on the last upgrade of HA (2021.11)

I think it's because I don't have a host configured. I uninstalled the ecodevice integration and reinstalled it : 

![CleanShot 2021-11-08 at 10 33 27](https://user-images.githubusercontent.com/2805640/140718036-f17494c9-a7e9-474e-9b0f-77c6e2858679.png)

Before I did that I could not (re)configure the host and port. Now I have this fields in the red square when I try to reinstall, but I cannot find a way to make the host field work (I tried http://192.168.1.77 and 192.168.1.77 ) but no luck :/

**Comment by edelans** [comment]
@Aohzan ok in fact my installation was indeed 2011.10 instead of 2011.11 (🤦‍♂️ )
so I installed 2011.11, but now as I have uninstalled your custom component and re-installed it, I cannot go through the configuration step : 


for the logger, I have added this to my `configuration.yaml` : 

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.ecodevices: debug
```


I get this in the log after trying to add the integration via the GUI : 

![CleanShot 2021-11-08 at 13 45 56](https://user-images.githubusercontent.com/2805640/140744534-d9a68c82-d768-4fcc-841b-4697ed249025.png)


```
File "/config/custom_components/ecodevices/config_flow.py", line 89, in async_step_user
return await self.async_step_params()
File "/config/custom_components/ecodevices/config_flow.py", line 101, in async_step_params
data_schema=vol.Schema(_get_params(self.base_input, user_input)),
File "/config/custom_components/ecodevices/config_flow.py", line 232, in _get_params
default=base_params[CONF_T1_UNIT_OF_MEASUREMENT],
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Aohzan** [comment]
Can you try with last version : https://github.com/Aohzan/ecodevices/releases/tag/3.0.1

**Comment by edelans** [comment]
still no luck 😭 

![CleanShot 2021-11-08 at 15 11 40](https://user-images.githubusercontent.com/2805640/140757159-bedd235e-f7bf-4199-9b99-9d7f4e57cb4c.png)

![CleanShot 2021-11-08 at 15 13 42](https://user-images.githubusercontent.com/2805640/140757205-52226751-e56c-4ff1-bd36-1a3d87c19f82.png)

![CleanShot 2021-11-08 at 15 14 10](https://user-images.githubusercontent.com/2805640/140757283-097c72d2-7c6f-4ed3-9537-0da88c353146.png)



I didn't manage to have better logs despite : 

![CleanShot 2021-11-08 at 15 14 27](https://user-images.githubusercontent.com/2805640/140757337-02ccbaf7-734b-4f03-bcfc-3830c013454a.png)

**Comment by Aohzan** [comment]
can you try 3.0.2 now :sweat_smile:

**Comment by edelans** [comment]
@Aohzan it works !

**Comment by edelans** [comment]
btw, when you setup the units in the initial config flow, you cannot reset them later ?

**Comment by Aohzan** [comment]
I added a option flow to do thtat, button Configure:
![image](https://user-images.githubusercontent.com/2736322/140884021-2f4a8d58-4d9c-4366-8f45-70382e472b63.png)
