### ISSUE TITLE
Créer une intité HC "Heure Creuse"

### ISSUE THREAD

**Issue by PasDeBol** [Aohzan/ecodevices#16]
Bonjour,

Je viens d'installer ton intégration à mon Home Assistant en test (je compte migrer de HomeSeer à HA).

Serait il possible d'avoir l'information/entité "Heure Creuse" directement depuis cette intégration?
Je m'en sers sur HomeSeer pour me faire des rappels genre "Démarrer le lave vaisselle" durant les heures creuses.

Merci
Jérôme

**Comment by Aohzan** [comment]
Bonjour,
Les informations heures creuses et autres sont disponible en attributs su l'entité principale,
