### ISSUE TITLE
Pas de données "Consommation d'énergie"

### ISSUE THREAD

**Issue by PasDeBol** [Aohzan/ecodevices#17]
Bonjour,

J'ai installé la contribution hier, via HACS, en sélectionnant uniquement Téléinfo 1, indiqué l'unité VA comme le screen de la doc.  L'entité sensor.teleinfo_1 fonctionne bien pour indiquer la puissance consommée, avec tous les arguments liés. Par contre , sensor.teleinfo_1_total reste figé à l'état "unknown" et rien ne s'affiche dans la partie Energie. Tout est à jour coté HA.

message coté energie:
statistics_not_defined
sensor.teleinfo_1_total
Entité indisponible
L'état de ces entités configurées n'est actuellement pas disponible :
sensor.teleinfo_1_total (unknown)
Grid consumption
Teleinfo 1 Total

Informations sur l’appareil
Eco-Devices
par GCE
Eco-Devices 192.168.2.84
Firmware: 1.05.26

Capteurs:
Teleinfo 1                  7 940 VA
Teleinfo 1  Total       Inconnu

Un truc que je n'ai pas fait?

Jérôme.

**Comment by Aohzan** [comment]
Bonjour,
Normalement rien de spécial à faire :thinking: 
Tu peux tester ces URL sur ton navigateur et envoyer le retour :
`http://192.168.2.84/status.xml`
`http://192.168.2.84/protect/settings/teleinfo1.xml`

**Comment by PasDeBol** [comment]
Bonjour.

status.xml:
<response>

<date>61411</date>
<time0>11:20</time0>
<config_hostname>ECO-DEVICES </config_hostname>
<config_mac>00:04:A3:A2:77:02</config_mac>
<http_port>80</http_port>
<T1_PPAP>8020</T1_PPAP>
<T2_PPAP>0</T2_PPAP>
<T1_PAPP>8020</T1_PAPP>
<T2_PAPP>0</T2_PAPP>
<T1_PTEC>HP</T1_PTEC>
<T2_PTEC>----</T2_PTEC>
<T1_ISOUSC>60</T1_ISOUSC>
<T2_ISOUSC>0</T2_ISOUSC>
<T1_IMAX>90</T1_IMAX>
<T1_IMAX1>90</T1_IMAX1>
<T1_IMAX2>0</T1_IMAX2>
<T1_IMAX3>0</T1_IMAX3>
<T2_IMAX>0</T2_IMAX>
<T2_IMAX1>0</T2_IMAX1>
<T2_IMAX2>0</T2_IMAX2>
<T2_IMAX3>0</T2_IMAX3>
<meter0>5</meter0>
<meter1>0</meter1>
<meter2>0</meter2>
<meter3>0</meter3>
<count0>1</count0>
<count1>2</count1>
<c0day>1</c0day>
<c1day>2</c1day>
<c0_fuel/>
<c1_fuel/>
<dnsstatus>0</dnsstatus>
<version>1.05.26</version>
</response>

teleinfo1.xml:
<response>



<T1_ADCO>031961844117</T1_ADCO>
<T1_OPTARIF>HC..</T1_OPTARIF>
<T1_ISOUSC>60</T1_ISOUSC>
<T1_BASE>0</T1_BASE>
<T1_HCHC>9744367</T1_HCHC>
<T1_HCHP>15321721</T1_HCHP>
<T1_EJPHN>0</T1_EJPHN>
<T1_EJPHPM>0</T1_EJPHPM>
<T1_BBRHCJB>0</T1_BBRHCJB>
<T1_BBRHPJB>0</T1_BBRHPJB>
<T1_BBRHCJW>0</T1_BBRHCJW>
<T1_BBRHPJW>0</T1_BBRHPJW>
<T1_BBRHCJR>0</T1_BBRHCJR>
<T1_BBRHPJR>0</T1_BBRHPJR>
<T1_PEJP>0</T1_PEJP>
<T1_PTEC>HP</T1_PTEC>
<T1_DEMAIN>----</T1_DEMAIN>
<T1_IINST>25</T1_IINST>
<T1_IINST1>25</T1_IINST1>
<T1_IINST2>0</T1_IINST2>
<T1_IINST3>0</T1_IINST3>
<T1_ADPS>61</T1_ADPS>
<T1_IMAX>90</T1_IMAX>
<T1_IMAX1>90</T1_IMAX1>
<T1_IMAX2>0</T1_IMAX2>
<T1_IMAX3>0</T1_IMAX3>
<T1_PPAP>5750</T1_PPAP>
<T1_PAPP>5750</T1_PAPP>
<T1_HHPHC>A</T1_HHPHC>
<T1_MOTDETAT>000000</T1_MOTDETAT>
<T1_PPOT>-</T1_PPOT>

</response>

**Comment by Aohzan** [comment]
c'est à cause de ça: `<T1_BASE>0</T1_BASE>`
si je comprends bien, quand tu es en HC/HP, `T1_BASE` est vide et il faut cumuler `T1_HCHC` et `T1_HCHP` pour connaitre le total de ta consommation ?

**Comment by PasDeBol** [comment]
Bien vu! 
Effectivement il faut la somme des deux pour la consommation globale.
Par contre , HA peut gérer le prix de l'énergie (donc 2 prix différents pour Heure Creuse et Pleine) donc ça peut être interressant de gérer les 2 totaux séparément et créer en plus le total des 2 (sans gestion de coût)

**Comment by Aohzan** [comment]
Ok il faut que j'implémente la gestion des HC/HP du coup

**Comment by PasDeBol** [comment]
Je vais patienter alors.

Merci.

**Comment by Aohzan** [comment]
je viens d'ajouter la gestion dans le code, tu peux tester l'installation du code sans passer par HACS ?

**Comment by PasDeBol** [comment]
Bonsoir,

ça a l'air de fonctionner:
J'ai refait "configuration" et cela m'a bien proposer de cocher "Heure Creuse". J'ai ajouter les nouvelles entités à Energie.
Il y a bien un total global, un total HC et un total HP avec les bonnes valeurs.
J'ai rien sur la partie graphique pour l'instant mais ça devrait venir.


Si tu veux améliorer, tu peux détecter automatiquement l'option tarifaire de l'utilisateur dans teleinfo1.xml avec la balise <T1_OPTARIF> . Pour moi: "HC.."


Je te remercie.

**Comment by Aohzan** [comment]
Top :+1: 
Ca sert à quelque chose de spécifier l'option tarifaire à home assistant ?

**Comment by PasDeBol** [comment]
> Ca sert à quelque chose de spécifier l'option tarifaire à home assistant ?

De paramétrer automatiquement ton intégration en fonction de Base ou HC/HP sans intervention de l'utilisateur.

**Comment by Aohzan** [comment]
ah oui dans le sens là, je préfère laisser le choix lors de la configuration pour éviter le bascule de l'un à l'autre si l'ecodevices renvoie une valeur erronée pour x raison, merci :+1:

**Comment by Aohzan** [comment]
HA remplie la table `statitics` dans sa db sur les entités de total, en regardant la différence régulièrement, normalement en max 2h tu as le graf qui apparait, il faut que HA soit up 24/7 je pense du coup oui
