### ISSUE TITLE
More than one eco devices

### ISSUE THREAD

**Issue by jorka57** [Aohzan/ecodevices#18]
Hello,

We have an installation with several Eco devices.
One for the three-phase and HP / HC Electric meter.
Another for the metering part of city water,
another for metering water for the swimming pool.
etc ...
How to integrate several Eco-devices in the same installation of Home Assistant. Because if I ask for a new integration, he tells me that there is already a first one.

Thanks

Jonathan

**Comment by Aohzan** [comment]
Hello,
It checks if the IP addresse or hostname is already used, can you paste me the error ?

**Comment by jorka57** [comment]
Ok I think I understand indeed:
I am using remote access for the moment via a hostname which remains the same but whose ports are different for each Eco device.

Eco device 1: ext-access.com:8001
Eco device 2: ext-access.com:8002
etc.

The same configuration for the IPX800V4 via the YAML works;)

So how can I successfully integrate my remote eco devices?
An update of your code or via YAML as for the IPX800V4?

Thanks ;)

**Comment by Aohzan** [comment]
I have to handle a couple of host and port instead of just host, I'll try to do that
(I can't do the same thing than ipx800v4 as it's an _old style_ config, but I will figured it out)

**Comment by Aohzan** [comment]
You can do it with the 4.0.0 release https://github.com/Aohzan/ecodevices/releases/tag/4.0.0
