### ISSUE TITLE
Pics de consommation

### ISSUE THREAD

**Issue by LudoBoyer** [Aohzan/ecodevices#20]
Bonjour,

Dans Energie sous HA j'ai très régulièrement des pics de consommation (par exemple aujourd'hui 50000kWh entre 3h et 4h de matin).
Est-ce un problème de votre l'intégration ou de utility meter ?

PS: dans l'historique de l'Ecodevice il n'y a pas ces pics de consommation.

Merci

**Comment by Aohzan** [comment]
Bonjour,
tu peux mettre l'historique du sensor teleinfo sur les 48 dernières heures ?

**Comment by Aohzan** [comment]
Je parlais de la vue historique, sur l'entité teleinfo total (ici que j'ai appelé linky)
![image](https://user-images.githubusercontent.com/2736322/157256529-691ffd64-9a73-4b2a-af52-ebf9c073b11e.png)

**Comment by Aohzan** [comment]
c'est lié au drop à ~73M renvoyé par l'Eco-Devices :(
actuellement j'exclue les valeurs égales à 0, normalement les valeurs inférieures à la précédente ne devraient pas être prise en compte :thinking:

**Comment by Aohzan** [comment]
Le soucis vient de l'Eco-devices qui a envoyé une valeur incorrecte à un moment donné, je vais voir pour éviter ça dans une mise à jour, en attendant, de ton côté tu dois aller supprimer toi même la valeur fautive dans la table statistics... (voir https://community.home-assistant.io/t/remove-faulty-readings-from-energy-dashboard-history/335555)

**Comment by LudoBoyer** [comment]
Merci pour le lien mais je sais pas quoi écrire et ni ou l'écrire.
Si tu pouvais encore m'aider ...

**Comment by LudoBoyer** [comment]
Avec ça c'est impec.

[https://community.home-assistant.io/t/how-to-fix-statistics-data-e-g-energy-data/360966](url)
