### ISSUE TITLE
Mode du compteur linky

### ISSUE THREAD

**Issue by cob94440** [Aohzan/ecodevices#21]
Bonjour

Le plugin est il compatible avec un linky en mode standard.
Je suis en jours zen et l'option tarifaire reste sur TH en mode historique.

**Comment by Aohzan** [comment]
Bonjour
Je remonte les infos tels que fournis par l'Eco Devices donc je dirais oui

**Comment by cob94440** [comment]
J'ai un appel avec eux, pour mettre a jour le firmware je vais leur demander. 
Dans leur forum certains ont mis en standard sans soucis d'autres n'ont plus rien.
Avec pour le moment un module teleinfo usb en historique je n'ai également pas les bonnes infos.
