### ISSUE TITLE
unable to find GCE ecodice in Integration

### ISSUE THREAD

**Issue by lio0909** [Aohzan/ecodevices#23]
Hello, 
I'm running HA 2022.7.7 in a docker. 
I did the manual install but I'm not able to find any GCE or ecodevice in the integration menu after restarting my HA.
Is there anything that needs to be activated, in configuration.yaml for example or what do I miss?
Thanks for your help.
Lionel

**Comment by Aohzan** [comment]
Hello,
Just to click on "Add integration" button and search GCE
maybe you can install it from HACS to be sure ?
