### ISSUE TITLE
issues with water counter

### ISSUE THREAD

**Issue by quentindavid** [Aohzan/ecodevices#24]
First, thanks for this HA component which is very cool !
I am trying to configure two water counters, but in the configuration I have no choice "water" in "type of counter". 

Also, in the units if I select L (liters), after it creates two entities which show L as unit, but the first one is the current water consumption, so it should be in L/min, and the second is the total per day, which is indeed in L.

Is it me or is it a bug ?

Thanks again!

**Comment by Aohzan** [comment]
You're welcome :)

Indeed, there is no device class for water counter : https://www.home-assistant.io/integrations/sensor/#device-class
So I have to implement the possibility to not choose a device class and have a generic sensor entity

You can set a different

**Comment by LudoBoyer** [comment]
Bonjour,

Maintenant il y a "water " dans les devices class (2022.10).
Pouvez mettre à jour.

Merci
