### ISSUE TITLE
Intégration compteur C1 panneau énergie

### ISSUE THREAD

**Issue by Jetblack31** [Aohzan/ecodevices#26]
Bonjour,

Je suis grand débutant sous Home Assistant. 
J’ai installé GCE Eco-Devices. Ca fonctionne. J’ai la téléinformation 1, Compteur C1 pour la pompe à chaleur, compteur C2 pour la production photovoltaïque.
Mon souci provient de l’intégration dans le panneau Energie.
Je voudrais intégrer la pompe à chaleur en appareil individuel, mais l’entité C1 n’est pas proposée dans le menu. Pourtant C1 est configuré comme Energy / Wh / kWh.
Pour C2, qui est configuré de la même manière, il n’y a pas de souci, j’ai pu l’intégrer pour la production PV.
Merci !
Jetblack

**Comment by Aohzan** [comment]
Bonjour
Est-ce que tu as quelque chose dans les logs concernant un problème d'unité de mesure ?
Si tu supprimes l'intégration et que tu l'ajoutes à nouveau, même soucis ?

**Comment by Jetblack31** [comment]
Bonsoir,
J'avais essayé mais je l'ai refait : suppression et réinstallation : ca y est, ca fonctionne parfaitement. Merci beaucoup et merci pour cet add-on.
Je profite au passage : j'ai un IPX800 V3, sais-tu si un add-on existe pour la V3 ?
Merci !

**Comment by Aohzan** [comment]
Non pas de mon côté je n'en ai pas eu
