### ISSUE TITLE
Sensor Meter 1

### ISSUE THREAD

**Issue by mimich25** [Aohzan/ecodevices#27]
Bonjour, je viens d'installer H.A. et je récupère bien les infos de mon ecodevice mais j'ai une erreur lorsque je l'integre au volet ENERGIE.
En effet le "meter 1" me permet de suivre ma consommation d'eau.
Voici ce que j'ai:
![image](https://user-images.githubusercontent.com/34286427/203319159-a60d2eb1-daed-4ddb-8d84-186582f56e43.png)

Avez-vous une solution pour ce problème?

**Comment by Aohzan** [comment]
bonjour, il faut ajouter l'entité qui a `Total` en suffixe, pas la principale ni la daily

**Comment by mimich25** [comment]
Je n'ai pas d'autres entités.
![image](https://user-images.githubusercontent.com/34286427/203322249-4549351c-c8c2-46b1-8d08-31cf617ceeb5.png)

**Comment by Aohzan** [comment]
quels sont les attributs de l'entité Total ?

**Comment by Aohzan** [comment]
onglet Informations

**Comment by mimich25** [comment]
![image](https://user-images.githubusercontent.com/34286427/203324710-67f46a14-8b5b-4186-86d8-5068dd80029e.png)

**Comment by Aohzan** [comment]
ah il n'y a pas ici, va dans les outils développeurs du coup, onglet Etats

**Comment by mimich25** [comment]
![image](https://user-images.githubusercontent.com/34286427/203330504-5fba2b46-d8a4-4440-a31a-a0773a9c3a4a.png)

**Comment by Aohzan** [comment]
il faut mettre `m³` pour total et pas `m3`

**Comment by mimich25** [comment]
après modification et redémarrage, c'est toujours pareil.
![image](https://user-images.githubusercontent.com/34286427/203336163-c9e4c0a9-4b22-4320-94b9-05d38d5baaef.png)

**Comment by Aohzan** [comment]
quelqu'un a réussi avec la même conf pourtant :thinking:  https://forum.gce-electronics.com/t/integration-eco-devices-home-assistant/10896/45?u=mati24

**Comment by mimich25** [comment]
ok c'est bon, en fait ici il faut actualiser avec la flèche en rond, il avait gardé m3.
![image](https://user-images.githubusercontent.com/34286427/203338058-a70082d4-09cd-4879-9113-dfccf4489a34.png)
Merci encore pour ce plugin et pour ta réactivité.
Très bon travail!
