### ISSUE TITLE
Capteur binaire basé sur le débit du compteur n°1 (C1)

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#28]
Bonjour,

Est-ce qu'il serait possible d'exposer un capteur binaire basé sur le débit du compteur n°1 (C1) ?
- Si consommation = 0 alors capteur binaire = False
- Si consommation != 0 alors capteur binaire = True

Ceci afin de déterminer s'il y'a une consommation d'eau dans la maison.

Cordialement

**Comment by Aohzan** [comment]
Hello, tu peux utiliser `[un template binary_sensor](https://www.home-assistant.io/integrations/template/#binary_sensor)` pour ça, en se basant sur la valeur du sensor (du genre, si valeur > 0)
