### ISSUE TITLE
User input malformed: expected str for dictionary value @ data['password']

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#29]
Bonjour,

Je rencontre un problème avec le plugin ecodevices. Je ne parviens pas à activer le compteur C1 dans Home Assistant et le plugin me retourne une erreur alors que je n'ai pas configuré de mot de passe sur mon EcoDevices.
`User input malformed: expected str for dictionary value @ data['password']`

![image](https://user-images.githubusercontent.com/938089/204082286-db16160e-6cc6-4b75-a7c4-1164ee10223f.png)

Pourtant la fonction d'authentification (Activer l'accès sécurisé) est bien décochée.
![image](https://user-images.githubusercontent.com/938089/204082366-2cec06e0-4fa0-4585-b309-d433cb7f9de0.png)

Cordialement

**Comment by Aohzan** [comment]
Hello, c'est obligatoire de mettre un mot de passe pour utiliser l'intégration (et c'est pas une mauvaise chose de protéger l'ecodevice ;) )

**Comment by lboue** [comment]
Merci pour la réponse.

Je ne souhaite pas ajouter de mot de passe pour ne pas compliquer l'accès à la WebUi.
Je reste assez septique car simplement en mettant un mot de passe puis en le retirant après cela fonctionne correctement.

**Comment by Aohzan** [comment]
oui après l'ajout ça fonctionne différemment, de mémoire sans mot de passe tu peux effacer les données et changer la configuration quand même
