### ISSUE TITLE
Pas de total en mode TH

### ISSUE THREAD

**Issue by spawnrider** [Aohzan/ecodevices#30]
Bonjour, 

Mon compteur Linky est en mode tarif de BASE. Du coup, je reçois au niveau de l'écodevice la valeur TH.

Au niveau intégration, je n'ai que le sensor de base qui est rempli, je n'ai pas de valeurs pour les HC/HP ni le Total.
<img width="507" alt="Capture d’écran 2022-11-26 à 17 35 20" src="https://user-images.githubusercontent.com/107427/204099180-4a3defe9-b5bd-4150-a62e-b415f4eda7d4.png">

Comme au niveau du panneau Energie, je ne peux pas saisir ce sensor de base mais uniquement le HC,HP ou total, je n'ai pas de données à ce niveau, est-ce normal ? 
<img width="726" alt="Capture d’écran 2022-11-26 à 17 37 20" src="https://user-images.githubusercontent.com/107427/204099268-06848c84-c574-4a21-839c-95efb52aa5cb.png">

**Comment by spawnrider** [comment]
Ok, je pense qu'il faut que je refasse la configuration et ne pas cocher HC/HP, c'est bien ça ?

**Comment by Aohzan** [comment]
hello, oui tout à fait :smile:
