### ISSUE TITLE
Valeur TI HP-HC vides / C1 OK

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#31]
Bonjour,

Je rencontre un souci depuis quelques jours avec le plugin ecodevices dans HA. Certaines valeurs ne remontent plus : 
![image](https://user-images.githubusercontent.com/938089/213848315-34ffe305-108b-45c7-8d84-df4e00092e12.png)

Cela fonctionnait correctement avant.

Le compteur d'eau remonte correctement par contre.

![image](https://user-images.githubusercontent.com/938089/213848365-fbed1e43-f8a4-4b52-9bb6-02dd4eaa1fcf.png)

Auriez vous une suggestion pour corriger cela ?

**Comment by Aohzan** [comment]
As-tu bien la dernière version (4.3.1) ?

**Comment by lboue** [comment]
Bien vu, avec la version 4.3.1, le problème est corrigé 👍 

![image](https://user-images.githubusercontent.com/938089/213870221-c30b4868-e71d-4763-aff6-0d6ba8c28052.png)
