### ISSUE TITLE
Depuis 2 jours, pas de remontée de données

### ISSUE THREAD

**Issue by Jetblack31** [Aohzan/ecodevices#32]
Bonjour,

J’ai un Ecodevices de première génération en FW 1.05.19 et depuis 2 jours je n’ai plus de remontée d’information. Rien ne change après avoir tout redémarrer.
En y regardant de près, le problème viendrait de globalstatus.xml. La téléinfo 1 se présente comme ceci dans le fichier :

```
<!--  TELEINFO 1  -->

...
<T1_BBRHPJR>0</T1_BBRHPJR>
<T1_PEJP>0</T1_PEJP>
<T1_PTEC>TH</T1_PTEC>
<T1_DEMAIN>
ADC</T1_DEMAIN>
<T1_IINST>14</T1_IINST>
<T1_IINST1>14</T1_IINST1>
```

Le problème pourrait venir du champ T1_DEMAIN qui se trouve codé sur 2 lignes au lieu d’une seule. En plus, je ne connais pas cette valeur « ADC ».

La téléinfo envoyé par le Linky aurait-elle changé ? 
J'ai également posté sur le forum GCE : https://forum.gce-electronics.com/t/pb-recent-ecodevices-1-globalstatus-xml/16626

Merci d’avance !

Bernard

**Comment by Aohzan** [comment]
Bonjour,
si je comprends bien la soucis est entre le compteur et l'ecodevices ? si c'est bien le cas je ne peux trop rien faire de mon côté. Sur le XML que je parse qui m'est envoyé par l'ecodevices, un retour à la ligne ne devrait pas poser de soucis, il faudrait voir si c'est le cas de GCE par le XML du compteur

**Comment by Jetblack31** [comment]
J'ai regardé de plus près : que ce soit dans le xml de globalstatus.xml ou de protect/settings/teleinfo1.xml
il y a ce saut de ligne au niveau de <T1_DEMAIN>
Je suis d'accord, si ce n'est qu'un saut de ligne, ca ne doit pas faire planter le parser XML. Sauf que ca fait planter tous les parsers XML que j'ai essayés. En fait, ce n'est pas un saut de ligne mais un caractère incorrect = 0002, qui n'est pas un caractère ascii de base.
Je vais essayer de reflasher le FW de l'Ecodevices pour voir si ca change quelque chose. Si ca ne change rien, c'est donc que la communication entre le linky et Ecodevices a changé, peut être une mise à jour du Linky ? si c'est le cas, je ne devrais pas être le seul à rencontrer le problème. Ci-joint le XML de téléinfo1 qui fait planter le parser. J'ai mis une extension txt car sinon je n'arrivais pas à le charger ici.


[teleinfo1.txt](https://github.com/Aohzan/ecodevices/files/10527390/teleinfo1.txt)

**Comment by Jetblack31** [comment]
![Capture d’écran 2023-01-28 à 14 49 49](https://user-images.githubusercontent.com/28689409/215270056-1e591fca-f2ce-44b1-91a4-88f8ff65d064.png)

**Comment by Aohzan** [comment]
Il y a un caractère anormal envoyé dans T1_DEMAIN : 

**Comment by Jetblack31** [comment]
Oui c'est ca. La téléinfo2 de l'ecodevices qui n'est connectée à rien n'a pas de souci, le fichier teleinfo2.xml est lisible. 
Je reflashe le FW de ED.
Merci beaucoup

**Comment by Jetblack31** [comment]
Bon, problème résolu en ré-installant le firmware. Désolé du dérangement !
