### ISSUE TITLE
following entities do not have the expected unit of measurement (either of CCF, ft³, m³, gal, L): sensor.meter_1_total (m3)

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#34]
Bonjour,

J'utilise cette intégration depuis plusieurs mois pour la partie électricité. Merci beaucoup car c'est très pratique pour suite la coût à venir. Cela fonctionne très bien comme on peut le voir sur le panneau ci-dessous:

![image](https://user-images.githubusercontent.com/938089/222952651-d39f6234-339c-4388-8acd-778435e3ca4f.png)

J'aimerais ajouté mon compteur d'eau branché sur l'entrée C1 mais je rencontre un souci côté HomeAssistant :

Voici le message d'erreur :
```
Unité de mesure inattendue : The following entities do not have the expected unit of measurement (either of CCF, ft³, m³, gal, L):
sensor.meter_1_total (m3)
```
![Capture d’écran 2023-03-05 102623](https://user-images.githubusercontent.com/938089/222952722-12663b13-0d1a-45f5-ab06-3a86fd13d4c9.png)

Voici le paramétrage qui me semble correct: 
![Capture d’écran 2023-03-05 102643](https://user-images.githubusercontent.com/938089/222952714-10becef5-a496-419e-b8f6-71fc38b00853.png)

Est-ce que j'aurais oublié quelque chose? 

Cordialement

**Comment by Aohzan** [comment]
Hello
Il faut que tu mettes `m³` et non `m3`

**Comment by lboue** [comment]
Merci pour l'info.
