### ISSUE TITLE
Entity sensor.meter_1 (<class 'custom_components.ecodevices.sensor.C1EdDevice'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing'

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#36]
Bonjour,

Je rencontre un souci avec ce plugin dans homeassistant pour lire les valeurs du compteur d'eau raccordé sur l'entrée C1 (type water)
J'ai consulté les logs et voici ce que j'y trouve :
```
Détails du journal (AVERTISSEMENT)
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:497
Integration: Capteur (documentation, issues)
First occurred: 08:14:52 (4 occurrences)
Last logged: 08:14:56
```

Il semble avoir un souci avec les entités suivantes

- sensor.meter_1
- sensor.meter_1_daily

```
Entity sensor.meter_1 (<class 'custom_components.ecodevices.sensor.C1EdDevice'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.meter_1_daily (<class 'custom_components.ecodevices.sensor.C1DailyEdDevice'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

Est-il faut faire une configuration supplémentaire pour que cela fonctionne ? 

![image](https://user-images.githubusercontent.com/938089/227151399-0a020110-424e-439f-81a1-4cc9b07fe1dc.png)

Voici ce que j'ai configuré dans le panneau "Energie" :  
![image](https://user-images.githubusercontent.com/938089/227151867-68e2f27f-988c-4bd3-86df-80d2e01943b3.png)

Cordialement

**Comment by Aohzan** [comment]
Bonjour,
Je suis en train de fixer le problème de ces messages, cependant ça ne devrait pas te bloquer

**Comment by lboue** [comment]
Merci pour ce retour. 
Il semblerai que cela bloque le cacul des couts pour une raison que j'ignore :
![image](https://user-images.githubusercontent.com/938089/227152944-a04e1c47-222a-4c16-9aff-7b59e7e60b0e.png)

J'ai du mal à savoir s'il faut indiquer le cout au L ou bien au m3 ici : 
![image](https://user-images.githubusercontent.com/938089/227153429-1d75d5a3-b918-4e20-9397-c59eb436033d.png)
