### ISSUE TITLE
sensor.meter_1 shall be a power sensor (not energy)

### ISSUE THREAD

**Issue by Mikael2588** [Aohzan/ecodevices#38]
Hello,

I have an impulse meter connected to the C1 input of the echo device.
In this configuration, the sensor.meter_1 returns the instantaneous power. So it's a power sensor and the unit shall be W (not Wh as mistakenly indicated in the echodevice interface).
I have the impression that there's a problem in the integration and that HA considers this sensor as an energy meter (even when the during the integration configuration meter_1 is set as power sensor).
Could you have a look on this topic?

The daily and total sensors are energy meters (Unit : Wh) and are correctly configured in the integration.

Thanks for your work.

**Comment by Aohzan** [comment]
Hello,
You can set the entity device class and the units in the integration options
