### ISSUE TITLE
Option Tempo

### ISSUE THREAD

**Issue by jfla76** [Aohzan/ecodevices#40]
Hello

can you integrate the option TEMPO in Ecodevice?

My ecodevice is connected to Linky

my XML file:
response
!--  GCE ELectronics - XML - XDEVICES - ECO-DEVICES - Copyright 2013  --
!--  APPUYEZ SUR LA TOUCHE F5 DE VOTRE CLAVIER POUR ACTUALISER  --
!--   TELEINFO 1   --
T1_ADCO xxxxxxxxxxxxx T1_ADCO
T1_OPTARIF  BBR* T1_OPTARIF
T1_ISOUSC  45 T1_ISOUSC
T1_BASE  0 T1_BASE
T1_HCHC  0 T1_HCHC
T1_HCHP  0 T1_HCHP
T1_EJPHN  0 T1_EJPHN
T1_EJPHPM  0 T1_EJPHPM
T1_BBRHCJB  17891273 T1_BBRHCJB
T1_BBRHPJB  19394501 T1_BBRHPJB
T1_BBRHCJW  3692737 T1_BBRHCJW
T1_BBRHPJW  3194502 T1_BBRHPJW
T1_BBRHCJR  527473 T1_BBRHCJR
T1_BBRHPJR  994873 T1_BBRHPJR
T1_PEJP  0 T1_PEJP
T1_PTEC  HPJB T1_PTEC
T1_DEMAIN  ---- T1_DEMAIN
T1_IINST  4 T1_IINST
T1_IINST1  4 T1_IINST1
T1_IINST2  0 T1_IINST2
T1_IINST3  0 T1_IINST3
T1_ADPS  0 T1_ADPS
T1_IMAX  90 T1_IMAX
T1_IMAX1  90 T1_IMAX1
T1_IMAX2  0 T1_IMAX2
T1_IMAX3  0 T1_IMAX3
T1_PPAP  1000 T1_PPAP
T1_PAPP  1000 T1_PAPP
T1_HHPHC  A T1_HHPHC
T1_MOTDETAT  000000 T1_MOTDETAT
T1_PPOT  - T1_PPOT
!--  FIN TELEINFO 1  --
response

Thanks for your work.

**Comment by Aohzan** [comment]
can you past the xml between ````` and with its `<xml>...`

**Comment by jfla76** [comment]
My Xml File:

''<response>



<T1_ADCO>061961525045</T1_ADCO>
<T1_OPTARIF>BBR*</T1_OPTARIF>
<T1_ISOUSC>45</T1_ISOUSC>
<T1_BASE>0</T1_BASE>
<T1_HCHC>0</T1_HCHC>
<T1_HCHP>0</T1_HCHP>
<T1_EJPHN>0</T1_EJPHN>
<T1_EJPHPM>0</T1_EJPHPM>
<T1_BBRHCJB>17895667</T1_BBRHCJB>
<T1_BBRHPJB>19410455</T1_BBRHPJB>
<T1_BBRHCJW>3692737</T1_BBRHCJW>
<T1_BBRHPJW>3194502</T1_BBRHPJW>
<T1_BBRHCJR>527473</T1_BBRHCJR>
<T1_BBRHPJR>994873</T1_BBRHPJR>
<T1_PEJP>0</T1_PEJP>
<T1_PTEC>HPJB</T1_PTEC>
<T1_DEMAIN>----</T1_DEMAIN>
<T1_IINST>3</T1_IINST>
<T1_IINST1>3</T1_IINST1>
<T1_IINST2>0</T1_IINST2>
<T1_IINST3>0</T1_IINST3>
<T1_ADPS>0</T1_ADPS>
<T1_IMAX>90</T1_IMAX>
<T1_IMAX1>90</T1_IMAX1>
<T1_IMAX2>0</T1_IMAX2>
<T1_IMAX3>0</T1_IMAX3>
<T1_PPAP>670</T1_PPAP>
<T1_PAPP>670</T1_PAPP>
<T1_HHPHC>A</T1_HHPHC>
<T1_MOTDETAT>000000</T1_MOTDETAT>
<T1_PPOT>-</T1_PPOT>

</response>''

**Comment by Aohzan** [comment]
J'ai ajouté les quelques attributs manquants dans la 4.7.0

**Comment by xbeaudouin** [comment]
Hello,
In fact in tempo mode we have "3" HPHC counters, as seen on XML : JB = jours bleus, JW = jours blanc et JR = jours rouges
```
<T1_BBRHCJB>17895667</T1_BBRHCJB>
<T1_BBRHPJB>19410485</T1_BBRHPJB>
<T1_BBRHCJW>3692737</T1_BBRHCJW>
<T1_BBRHPJW>3194502</T1_BBRHPJW>
<T1_BBRHCJR>527473</T1_BBRHCJR>
<T1_BBRHPJR>994873</T1_BBRHPJR>
```

The Teleinfo counter set in the code seems only working in "traditional" HP/HC mode. I am starting to migrate my domotic into Home Assistant, so, for now I cannot submit a PR...
Maybe we can discuss about that somewhere else?

**Comment by Aohzan** [comment]
les attributs remontent sur l'entité de conso instantannée, il est ensuite possible de créer des entités dédiées via les template, voir https://github.com/Aohzan/ecodevices#more-entities
