### ISSUE TITLE
Ajout Entrée Water

### ISSUE THREAD

**Issue by gregcam78** [Aohzan/ecodevices#42]
Bonjour, 
l'intégration du compteur électrique fonctionne parfaitement bien. 
Depuis plusieurs semaines, j'essaye de rajouter la partie eau dans le module energy.
La remontée d'information via les capteurs est nickel : 
![image](https://github.com/Aohzan/ecodevices/assets/46299895/9e2cf17d-cba9-4d1e-ac01-e899b3d63c61)
J'ai bien fait attention à positionner m³ au lieu de m3.
Quand je souhaite rajouter le capteur water total dans la consommation d'eau, le capteur d'apparait dans la liste déroulante.
![image](https://github.com/Aohzan/ecodevices/assets/46299895/00ec8056-6e5b-4bec-bcb7-c0ad9f52b19a)
Avez vous une idée du pourquoi du comment, svp ?
Merci d'avance.
Greg
HA 2023.9.1

**Comment by Aohzan** [comment]
Bonjour
Dans la configuration de l'intégration, le type est bien à water?

**Comment by gregcam78** [comment]
Bonjour, 
merci de votre retour rapide.
Oui, type = water.
![image](https://github.com/Aohzan/ecodevices/assets/46299895/007b1d45-8c04-4857-ad9d-2c48174f7667)
Greg

**Comment by Aohzan** [comment]
Tu peux poster les attributs de l'entité total?

**Comment by gregcam78** [comment]
Ci dessous : 
![image](https://github.com/Aohzan/ecodevices/assets/46299895/63ec4979-c752-4edd-b396-7f27e23d287b)
Cdt

**Comment by Aohzan** [comment]
![Screenshot_20230915-211948.png](https://github.com/Aohzan/ecodevices/assets/2736322/974a4dd4-ee49-4d8b-936b-f48429300077)

It's weird, it should work, see mine
