### ISSUE TITLE
 homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info: device info needs to either describe a device, link to existing device or provide extra information.

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#43]
Bonjour,

Je n'arrive plus à charger le module ecodevices dans HomeAssistant. Pourriez-vous m'aider à identifier le problème ?

![image](https://github.com/Aohzan/ecodevices/assets/938089/d4055d03-834f-42ff-8448-776cccf6fe7c)

### Debug
Voici ce que donne le debug : 

    2023-11-04 13:47:12.296 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Eco-Devices 192.168.1.7:80 for ecodevices
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
        result = await component.async_setup_entry(hass, self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/config/custom_components/ecodevices/__init__.py", line 93, in async_setup_entry
        device_registry.async_get_or_create(
      File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 511, in async_get_or_create
        device_info_type = _validate_device_info(config_entry, device_info)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 165, in _validate_device_info
        raise DeviceInfoError(
    homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'configuration_url': 'http://192.168.1.7:80', 'connections': {('mac', '00:04:A3:A2:37:81')}, 'default_name': 'Eco-Devices 192.168.1.7:80', 'identifiers': {('ecodevices', '00:04:A3:A2:37:81')}, 'manufacturer': 'GCE', 'model': 'Eco-Devices', 'sw_version': '1.05.12'} for 'ecodevices' config entry: device info needs to either describe a device, link to existing device or provide extra information.

### Ma configuration

- Home Assistant 2023.8.3
- Supervisor 2023.10.1
- Operating System 10.2
- Frontend 20230802.1 - latest

### HA core 2023.8
Il semble avoir eu un changement avec Home Assistant core 2023.8 : 

- Les appareils sont maintenant [catégorisés en 3 types](https://developers.home-assistant.io/docs/device_registry_index/#categorizing-to-device-info) par Home Assistant et chacun de ces types ont un ensemble de propriétés à respecter.
    - Link
    - Primary
    - Secondary
- La déclaration précédente de l'appareil définissait à la fois un default_manufacturer et un manufacturer ainsi qu'un default_model et un model. Les defaults étant des constantes au cas où l'ADCO dont le vrai constructeur et modèle sont dérivés une fois la ligne lue sur le lien série (voir entité "Adresse du compteur") ne pouvaient être parsée correctement lors de la lecture du lien série (une sécurité en somme).
- Mélanger les 2 n'est plus permis et la correction a été de définir les manufacturer, model et name (afin de correspondre à la définition de type Primary) et de retirer les default_manufacturer, default_model et default_name qui ne sont pas accepté en type Primary mais seulement Secondary.

Cordialement

**Comment by Aohzan** [comment]
Peux-tu mettre à jour à la fois Home Assistant et le custom component ?
