### ISSUE TITLE
Problème intégration avec eau 

### ISSUE THREAD

**Issue by CABESTAN-NET** [Aohzan/ecodevices#44]
![2023-12-04 09-36-01_Outils de développement – Home Assistant](https://github.com/Aohzan/ecodevices/assets/152845805/2d800102-a80b-478d-8811-baeacc7a8093)
Bonjour
J'essaie de paramétrer mon GCE avec HA mais je rencontre des problème avec le compteur d'eau. Je ne l'ai pas le suivi d'energie et surtout les unités sont en W, KW au lieu de L et m³
J'ai lu et relu qu'il fallait mettre en water alors je suis allé dans developer-tools/state et j'ai corrigé les valeurs mais elles reviennent sur energy.
Je débute avec HA et là je suis totalement perdu.

Merci

**Comment by Aohzan** [comment]
Le paramétrage des unités est dans la deuxième étape de configuration (initiale ou via l'intégration)
