### ISSUE TITLE
Ecodevice + Linky - compteur Total

### ISSUE THREAD

**Issue by tourdumonde** [Aohzan/ecodevices#45]
Bonjour, 
J'utilise cette intégration depuis maintenant quelques années, merci beaucoup pour le travail réalisé.

Depuis que je suis passé à l'option "Tempo" d'EDF, il n'y a plus aucune valeur remontée dans "Teleinfo Total".
![image](https://github.com/Aohzan/ecodevices/assets/82966049/16cce5a3-c6b1-4ae2-be4b-56eb106a747a)

J'ai réinstallé plusieurs fois, essayé en cochant / décochant "HC HP".

Comment puis-je faire pour retrouver cette valeur totale et la réintégrer dans le dashboard ernergie  ? 

Voici le fichier XML: 
```xml
<response>
<!--  GCE ELectronics - XML - XDEVICES - ECO-DEVICES - Copyright 2013  -->
<!--  APPUYEZ SUR LA TOUCHE F5 DE VOTRE CLAVIER POUR ACTUALISER  -->
<!--   TELEINFO 1   -->
<T1_ADCO>062064319211</T1_ADCO>
<T1_OPTARIF>BBR(</T1_OPTARIF>
<T1_ISOUSC>30</T1_ISOUSC>
<T1_BASE>0</T1_BASE>
<T1_HCHC>0</T1_HCHC>
<T1_HCHP>0</T1_HCHP>
<T1_EJPHN>0</T1_EJPHN>
<T1_EJPHPM>0</T1_EJPHPM>
<T1_BBRHCJB>20944454</T1_BBRHCJB>
<T1_BBRHPJB>271684</T1_BBRHPJB>
<T1_BBRHCJW>28279</T1_BBRHCJW>
<T1_BBRHPJW>72754</T1_BBRHPJW>
<T1_BBRHCJR>6742</T1_BBRHCJR>
<T1_BBRHPJR>21695</T1_BBRHPJR>
<T1_PEJP>0</T1_PEJP>
<T1_PTEC>HPJB</T1_PTEC>
<T1_DEMAIN>----</T1_DEMAIN>
<T1_IINST>1</T1_IINST>
<T1_IINST1>1</T1_IINST1>
<T1_IINST2>0</T1_IINST2>
<T1_IINST3>0</T1_IINST3>
<T1_ADPS>0</T1_ADPS>
<T1_IMAX>90</T1_IMAX>
<T1_IMAX1>90</T1_IMAX1>
<T1_IMAX2>0</T1_IMAX2>
<T1_IMAX3>0</T1_IMAX3>
<T1_PPAP>310</T1_PPAP>
<T1_PAPP>310</T1_PAPP>
<T1_HHPHC>A</T1_HHPHC>
<T1_MOTDETAT>000000</T1_MOTDETAT>
<T1_PPOT>-</T1_PPOT>
<!--  FIN TELEINFO 1  -->
</response>
```

Merci.

Belle journée.

**Comment by Aohzan** [comment]
@jfla76 je crois que je viens de comprendre ton soucis avec ce que décrit @tourdumonde 
il faut pouvoir dire qu'on utilise l'option tempo, que vous ayez une entité qui totalise tous les T1_BBRH* ? Ainsi qu'une entité par T1_BBRH* ?

**Comment by tourdumonde** [comment]
@Aohzan, L’option Tempo propose 6 prix du kilowattheure différents, qui dépendent des heures de la journée (heures pleines et creuses) et des couleurs des jours: jour bleu, jour blanc et jour rouge. 

T1_BBRHCJB = Jour bleu heures creuses
T1_BBRHPJB =  Jour bleu heures pleines
T1_BBRHCJW =  Jour blanc heures creuses
T1_BBRHPJW =  Jour blanc heures pleines
T1_BBRHCJR = Jour rouge heures creuses
T1_BBRHPJR = Jour rouge heures pleines

![image](https://github.com/Aohzan/ecodevices/assets/82966049/06f8d4a9-8e7d-49dd-90f7-90b33de0c6a1)

**Comment by Aohzan** [comment]
oui mais ce que j'aimerais savoir c'est comment vous voulez que ça se traduise côté Home-Assistant

**Comment by Aohzan** [comment]
Je viens de sortir une beta qui permet de choisir le mode tempo pour gérer ça correctement: https://github.com/Aohzan/ecodevices/releases/tag/5.0.0b1
Si vous pouvez tester et me redire (faire configurer et choisir tempo dans la liste)

**Comment by tourdumonde** [comment]
> Je viens de sortir une beta qui permet de choisir le mode tempo pour gérer ça correctement: https://github.com/Aohzan/ecodevices/releases/tag/5.0.0b1 Si vous pouvez tester et me redire (faire configurer et choisir tempo dans la liste)

Mise à jour faite. J'ai bien l'option Tempo :)
Les nouvelles entités ont été crées, les valeurs remontent correctement.
J'ai configuré le dashboard énergie. Il faut maintenant attendre un peu pour qu'il se mette à jour.
![image](https://github.com/Aohzan/ecodevices/assets/82966049/ece55fd0-52c8-4cd8-8cf7-df00498b7997)

Merci @Aohzan

**Comment by Aohzan** [comment]
top je release

**Comment by tourdumonde** [comment]
> top je release
Ca semble être ok pour les jours bleus HP, par contre si je mets "teleinfo 1 total" dans le dashboard energy, j'ai une valeur négative.
![image](https://github.com/Aohzan/ecodevices/assets/82966049/8fa38b90-e13a-4dac-9209-9ee1f1179dfc)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/245c514e-5f3b-4731-beb7-73ac996adac7)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/1d9bb7ea-6af2-46c9-9ada-4e8d50e3be77)

Merci

**Comment by Aohzan** [comment]
peux tu me montrer la valeur de toutes les entités teleinfo

**Comment by tourdumonde** [comment]
![image](https://github.com/Aohzan/ecodevices/assets/82966049/4e3bec83-c2d1-4f29-be6d-027f2c867392)

![image](https://github.com/Aohzan/ecodevices/assets/82966049/4f972f3c-46b0-444f-b7bb-764758bdfd0d)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/8d88621f-e9cd-4b56-8ed3-74cecef24d9d)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/f5c8b316-a08c-4f57-95f3-14f74ecefbf7)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/11630dab-aa83-48d0-9828-3a5ca1b00bac)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/e6192f69-42b5-4342-9daa-a9b06b5bbc71)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/757355a8-8af4-4b8a-a120-75a84f1cdff3)
![image](https://github.com/Aohzan/ecodevices/assets/82966049/94ef3eb7-1809-44a1-a3da-66feb80b1e7e)

XML
<response>



<T1_ADCO>062064319211</T1_ADCO>
<T1_OPTARIF>BBR(</T1_OPTARIF>
<T1_ISOUSC>30</T1_ISOUSC>
<T1_BASE>0</T1_BASE>
<T1_HCHC>0</T1_HCHC>
<T1_HCHP>0</T1_HCHP>
<T1_EJPHN>0</T1_EJPHN>
<T1_EJPHPM>0</T1_EJPHPM>
<T1_BBRHCJB>20944454</T1_BBRHCJB>
<T1_BBRHPJB>274939</T1_BBRHPJB>
<T1_BBRHCJW>28279</T1_BBRHCJW>
<T1_BBRHPJW>72754</T1_BBRHPJW>
<T1_BBRHCJR>6742</T1_BBRHCJR>
<T1_BBRHPJR>21695</T1_BBRHPJR>
<T1_PEJP>0</T1_PEJP>
<T1_PTEC>HPJB</T1_PTEC>
<T1_DEMAIN>----</T1_DEMAIN>
<T1_IINST>2</T1_IINST>
<T1_IINST1>2</T1_IINST1>
<T1_IINST2>0</T1_IINST2>
<T1_IINST3>0</T1_IINST3>
<T1_ADPS>0</T1_ADPS>
<T1_IMAX>90</T1_IMAX>
<T1_IMAX1>90</T1_IMAX1>
<T1_IMAX2>0</T1_IMAX2>
<T1_IMAX3>0</T1_IMAX3>
<T1_PPAP>470</T1_PPAP>
<T1_PAPP>470</T1_PAPP>
<T1_HHPHC>A</T1_HHPHC>
<T1_MOTDETAT>000000</T1_MOTDETAT>
<T1_PPOT>-</T1_PPOT>

**Comment by Aohzan** [comment]
j'ai l'impression que c'est normal, le total est bien la somme de tous les autres
c'est juste que Home-Assistant a mal géré la migration niveau statistique, dans les Dev tools tu peux corriger pour l'entité total en supprimante la valuer avec le `- xxx`

**Comment by jfla76** [comment]
Merci pour cette mise à jour.

**Comment by tourdumonde** [comment]
> j'ai l'impression que c'est normal, le total est bien la somme de tous les autres c'est juste que Home-Assistant a mal géré la migration niveau statistique, dans les Dev tools tu peux corriger pour l'entité total en supprimante la valuer avec le `- xxx`

Tout est OK maintenant.
Merci pour cette mise à jour.
