### ISSUE TITLE
Question pour afficher le tarif en cours HP/HC dans HomeAssistant

### ISSUE THREAD

**Issue by lboue** [Aohzan/ecodevices#46]
Bonjour,

Je cherche a afficher dans HomeAssistant le tarif en cours HP/HC. Je crois c'est en lien avec la valeur _T1_OPTARIF_ que l'on retrouve dans le fichier XML:
`<T1_OPTARIF>HC..</T1_OPTARIF>`

Le but est de commander des appareils en heures creuses.

Savez-vous comment faire cela ?

Cordialement

**Comment by Aohzan** [comment]
Bonjour

L'info est disponible dans les attributs de l'entité, sous le nom `option_tarifaire` : 
https://github.com/Aohzan/ecodevices/blob/master/custom_components/ecodevices/const.py#L54

**Comment by lboue** [comment]
Merci @Aohzan
