### ISSUE TITLE
Compteur d'eau, tableau de bord énergie.

### ISSUE THREAD

**Issue by Niepce26** [Aohzan/ecodevices#47]
Bonjour, débutant en domotique j'ai réussi à installer ce module complémentaire ainsi qu'à faire apparaître les valeurs dans le tableau de bord "énergie"

Toutefois, concernant mes données du compteur d'eau dans le tableau de bord "énergie" j'ai la valeur de la consommation journalière de la veille qui s'enregistre en négatif à minuit.

Pas persuadé d'être très claire quelques captures d'écran devrait aider 

En tout cas merci pour votre travail.

![Screenshot_2024-03-06-05-28-09-763_io homeassistant companion android~2](https://github.com/Aohzan/ecodevices/assets/162018450/49f9584c-9db5-4765-8198-a13664479f94)

![Screenshot_2024-03-06-05-31-16-167_io homeassistant companion android~2](https://github.com/Aohzan/ecodevices/assets/162018450/ff5da2fc-6f85-427e-bfd3-7e9509abb695)

**Comment by Aohzan** [comment]
Peux-tu montrer l'historique de ton entité sensor total

**Comment by Niepce26** [comment]
[history.csv](https://github.com/Aohzan/ecodevices/files/14506579/history.csv)

Bonjour, 

Ci-joint l'historique du 05 au 06 mars, c'est bien ca que vous souhaitez ?

**Comment by Aohzan** [comment]
les meter_1_total et meter_2_total ont l'air correct, c'est bien une des deux entité utilisée ? quelle configuration dans l'intégration ?

**Comment by Niepce26** [comment]
D'accord mon erreur doit venir de la car pour l'intégration dans le tableau de bord "énergie" j'ai choisi l'entité meter 1 Daily.

![image](https://github.com/Aohzan/ecodevices/assets/162018450/bfb46069-652f-4ff3-92dd-42a955f3f4f6)
