### ISSUE TITLE
teleinfo total renvoi une valeur trop élevé

### ISSUE THREAD

**Issue by byboleymar** [Aohzan/ecodevices#49]
Hello!
Je constat que régulièrement, le "teleinfo total" renvoi une valeur fausse (et énorme), je peux la corriger manuellement par le module "developer-tools/statistics" puis "ajuster la somme".

Mais comment faire pour remédier à cette erreur sans action manuelle?

![2024-07-15_17h32_12](https://github.com/user-attachments/assets/627b19df-c7d9-4fbe-8a78-80a752f24f43)
![2024-07-15_17h42_01](https://github.com/user-attachments/assets/7a0fce9d-f8df-4b19-ab77-411d138b67f7)

Thx !!

**Comment by Aohzan** [comment]
Hello, tu peux m'afficher l'historique du sensor stp

**Comment by byboleymar** [comment]
Est-ce valeur que tu voulais ? 

![2024-07-16_09h58_58](https://github.com/user-attachments/assets/36e7731e-4c81-4eed-abee-4d678dc6d44c)
![2024-07-16_09h59_58](https://github.com/user-attachments/assets/8d248078-0b18-4306-b42c-2705fa6ab7db)

**Comment by Aohzan** [comment]
oui,
le soucis vient des chutes de la valeur en bas, il y a déjà une protection pour éviter les retour à 0, mais chez toi ça n'a pas l'air de revenir à 0, peux-tu faire un zoom sur 2-3 chute de valeur pour voir à combien ça descend

**Comment by byboleymar** [comment]
![2024-07-16_10h22_50](https://github.com/user-attachments/assets/f0fede5e-38c2-4357-9922-c367c9d7450b)
![2024-07-16_10h22_58](https://github.com/user-attachments/assets/d46bfda5-1a77-46ef-be29-960d348cd617)
![2024-07-16_10h23_08](https://github.com/user-attachments/assets/422a3e89-b63d-436d-b0be-87245e84e2e8)

**Comment by Aohzan** [comment]
du coup comme ça redescend pas à 0 je sais pas trop quoi faire
tu pourrais ouvrir un ticket à GCE pour voir avec eux pourquoi ça arrive ?

**Comment by byboleymar** [comment]
ok, je leur transmet ce ticket.

**Comment by byboleymar** [comment]
"GCE: Je ne comprends pas bien le problème, HA recupère parfois des valeurs trop faibles donc cela donne une consommation très grande !? "

Plus, coté GCE, il ne semble pas avoir d'anomalie:

![2024-07-16_12h15_00](https://github.com/user-attachments/assets/c1e5a51d-71a7-4512-a94f-51b014c05593)
![2024-07-16_12h15_21](https://github.com/user-attachments/assets/300a639d-50fe-4244-a696-cc64afe9739b)

**Comment by Aohzan** [comment]
on lit la valeur renvoyée par l'API de l'EcoDevices donc je sais pas trop ce qu'on peut faire :disappointed:

**Comment by byboleymar** [comment]
Ne pas enregistrer le résultat s'il semble anormal par rapport au control précédent?
faire un retry, garder la valeur précédente ou remonter une anomalie ?

**Comment by Aohzan** [comment]
oui mais c'est plus simple à dire qu'à faire, tu n'as pas accès à l'historique des données comme ça

**Comment by KevinGCE** [comment]
Hello :)
L'EcoDevice transmet les valeurs qu'elle reçoit, il n'y a pas de raison qu'elle soient fausses, à moins que ce soit les valeurs que lui envoie le compteur, dans ce cas, je ne vois pas ce qu'il serait possible de faire...
Il y a peut être une sécurité sur l'EcoDevice pour ne pas prendre en compte une valeur abhérente si elle est isolée mais ca, c'est fait dans le traitement des l'information, après qu'elle soit récupérée et la valeur transmise via l'API est la valeur brute...

Est-ce qu'il serait possible de récupérer la trame TIC qui pose problème ?

**Comment by Aohzan** [comment]
@KevinGCE tu pourrais me dire quelles vérifications sont mises en place après la récupération de la valeur ? Voir si je peux l'implémenter aussi

Pour la trame, il faudrait que @byboleymar ailleur requêter l'API au moment où il y un soucis mais ça ne va pas être évident.
Côté code je reprends juste la valeur renvoyées par `T1_BASE` ou `T1_BBRHCJB`...

**Comment by KevinGCE** [comment]
Oui mais je pense que ca doit arriver une fois sur 1000 et étant donné qu'il y a une révolution toutes les 1.9s environ, ça fait un erreur potentielle toutes les 2000s, soit environ toutes les 30 minutes... Pour qu'on tombe dessus pile poil au démarrage de HA, faudrait pas avoir de bol mais c'est potentiellement possible...

**Comment by Aohzan** [comment]
j'ai trouvé un moyen de récupérer la dernière valeur, j'ai sorti une version 5.2.0 https://github.com/Aohzan/ecodevices/releases/tag/5.2.0
@byboleymar je ferme cette issue, si jamais HA reçoit une valeur jugée incohérente, il y aura un Warning dans les logs, peux tu me redire si tu en vois prochainement ?  Et si jamais le soucis se reproduit, réouvre l'issue

**Comment by byboleymar** [comment]
Merci à vous 2 !!!
le bug n'étant pas régulier, je reviendrai dans une semaine.
