### ISSUE TITLE
Ecodevice and node red

### ISSUE THREAD

**Issue by Bercolly** [Aohzan/ecodevices#51]
In a node red stream, I capture the state changes of the ecodevice to detect possible ecodevice failures.

However, I notice that the information provided by the node red node 'The Poll State node' is not updated.

In particular, the fields:
last_changed: "2024-09-30T17:09:15.436Z"
last_reported: "2024-09-30T17:09:15.436182+00:00"
last_updated: "2024-09-30T17:09:15.436Z"

always display the same values.

And the field 'timeSinceChangedMs' displays a value in milliseconds of 6554849 while the node is polled every two minutes, i.e.: 120000 ms.

I use:
 Core 2024.9.3 
Supervisor 2024.09.1 ​​
Operating System 13.1 
Ecodevice 5.2.0 
Node red 18.0.5 
Node red companion: v4.1.1

**Comment by Aohzan** [comment]
I don't think those value are managed in this integration but more in home assistant core :thinking: 
Here I don't managed any datetime, I just tell to HA the last value of each entity

**Comment by Bercolly** [comment]
Thanks for your reply.
