### ISSUE TITLE
Lost sensor.meter_1_total with 5.3.0 version

### ISSUE THREAD

**Issue by DJJL** [Aohzan/ecodevices#52]
Hi,
with the last version 5.3.0, I lost entity sensor.meter_1_total, for water
why ? it's bug of new version ?
Sensor.meter_1 and sensor.meter_1_daily are ok
JL

A solution ? : I have just change de name entity "sensor.meter_1_total" to "sensor.meter_2_total" and now I have the value (64,51m3), why it's ok now ? I don't know

Now it's ok for 3 entities : 
- sensor.meter_1
- sensor.meter_1_daily
- sensor.meter_2_total

**Comment by Aohzan** [comment]
Hello,
I don't have the issue on my side, can you paste debug logs please

**Comment by DJJL** [comment]
I don't find the debug log, is it /homeassistant/home-assistant.log.fault ?

Now faor entities CGE : 
![image](https://github.com/user-attachments/assets/e78e5d87-72e2-4229-a685-dd86e1c70180)

**Comment by DJJL** [comment]
Oui, fait après la mise à jour, mais
no change, sensor.meter_1_total is lost (indisponible) since upgrade

**Comment by Aohzan** [comment]
c'est pour avoir les logs que j'ai mis ça

**Comment by DJJL** [comment]
ok, mais où est il enregistré ?

**Comment by Aohzan** [comment]
quand on désactive les l'enregistrement il les télécharge automatiquement

**Comment by DJJL** [comment]
exact, merci pour l'info,
Ce n'est pas un log local mais un log général qui est téléchargé lors de la désactivation, 1 ligne concerne Ecodevice sur les 26403... 
![image](https://github.com/user-attachments/assets/4e8c8abc-5499-4b12-b03a-9fc91d3e9ee1)

**Comment by Aohzan** [comment]
même en faisant un recharger de l'intégration entre les deux ?

**Comment by DJJL** [comment]
fait à l'instant, sur les 63050, juste, il y a déjà plus de lignes pour l'ecodevice, 
![image](https://github.com/user-attachments/assets/cbc394de-e102-4ff0-8279-76814e601f19)
pas de problème avec cette info ci dessus je suppose ;-) ...
![image](https://github.com/user-attachments/assets/26945a69-3d85-4676-aca3-d013e0e9cd8e)
![image](https://github.com/user-attachments/assets/2164721a-7124-4bba-87a1-d51a38c50922)
![image](https://github.com/user-attachments/assets/9e20ebbb-177d-4f22-b10f-1ab20d441d30)
![image](https://github.com/user-attachments/assets/05c65def-af5f-4b94-a35e-79c7d61ce32f)
![image](https://github.com/user-attachments/assets/741bc61b-49db-4442-9536-899b4207d7e7)
![image](https://github.com/user-attachments/assets/29a5f9b6-9379-44b5-a2ff-c282991335f5)
![image](https://github.com/user-attachments/assets/58c0299f-530f-4969-90f5-d7495506e3e1)
![image](https://github.com/user-attachments/assets/7b685b15-b93d-4ef8-8e28-bc282790a536)
![image](https://github.com/user-attachments/assets/bb5d1713-71da-4c57-840d-80e5333451f4)
![image](https://github.com/user-attachments/assets/0de9acfe-3ba4-48ec-8bdd-f174f7b394ad)
...
Là j'ai voulu remettre l'entité d'origine mais évidemment pas possible : 
![image](https://github.com/user-attachments/assets/9d08fb3f-cfef-4a67-82d1-194c095faa15)
![image](https://github.com/user-attachments/assets/b07757a3-bff4-4f06-8863-2ade251b038a)

![image](https://github.com/user-attachments/assets/51cf3acf-141f-4c15-a158-490e3f948e7c)
![image](https://github.com/user-attachments/assets/e3e35367-1362-4169-b0b2-e2bbe1d08486)
![image](https://github.com/user-attachments/assets/136c7b67-0f31-4aad-acb3-6bb6030628a7)
![image](https://github.com/user-attachments/assets/41db2e54-ada9-4ed0-96f2-5cad20837e2c)

ca fonctionne donc en ayant précédemment changé le nom de l'entité en "sensor.meter_2_total"

Merci Aohzan et sorry pour l'absence de log lors de la mise à jour qui aurait permit de voir l'anomalie.

**Comment by DJJL** [comment]
tu as mille fois raison ! "copy/paste" est plus clair, c'est corrigé (j'étais ailleurs.... ;-) )
Je viens de retester le retour à l'entité d'origine, sensor.meter_1_total, impossible car évidemment HA signale que cette ID existe déjà (mais où ?...)
![image](https://github.com/user-attachments/assets/77c316a5-8958-4f48-a6e1-34c31165ee90)

**Comment by Aohzan** [comment]
tu peux coller les logs autour de cette ligne : 
```if self._last_state is None or value >= float(self._last_state):```

**Comment by DJJL** [comment]
voilà, en prenant large autour de cette partie : 

2024-10-03 16:08:09.038 WARNING (MainThread) [homeassistant.components.min_max.sensor] Units of measurement do not match for entity sensor.conso_instantanee_brut
2024-10-03 16:08:09.295 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.meter_1_total for domain sensor with platform ecodevices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecodevices/sensor.py", line 566, in native_value
    if self._last_state is None or value >= float(self._last_state):
                                            ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'
2024-10-03 16:08:09.549 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.smartmeter_production_delectricite to <Job track state_changed event {'sensor.sma_sma_o_e_energy_tot_du_jour_446', 'sensor.smartmeter_production_delectricite'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=(automation:
  trigger:
    platform: state
    entity_id:
      - sensor.sma_sma_o_e_energy_tot_du_jour_446
      - sensor.smartmeter_production_delectricite
  action:
    - service: notify.notify
      data_template:
        message: >
          {% set result = states('sensor.sma_sma_o_e_energy_tot_du_jour_446') | float - states('sensor.smartmeter_production_delectricite') | float %}
          Le résultat de la soustraction est {{ result }}
    - condition: template
      value_template: "True") renders=456>: <RenderInfo Template<template=(automation:
  trigger:
    platform: state
    entity_id:
      - sensor.sma_sma_o_e_energy_tot_du_jour_446
      - sensor.smartmeter_production_delectricite
  action:
    - service: notify.notify
      data_template:
        message: >
          {% set result = states('sensor.sma_sma_o_e_energy_tot_du_jour_446') | float - states('sensor.smartmeter_production_delectricite') | float %}
          Le résultat de la soustraction est {{ result }}
    - condition: template
      value_template: "True") renders=456> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sma_sma_o_e_energy_tot_du_jour_446', 'sensor.smartmeter_production_delectricite'}) rate_limit=None has_time=False exception=None is_static=False>}>>>

**Comment by Aohzan** [comment]
tu peux essayer la 5.3.1

**Comment by DJJL** [comment]
bingo, j'ai pu remettre le "sensor.meter_1_total" sans erreur de la part de HA,
je regarderai si tout est ok tantôt car je dois partir là
Merci

**Comment by DJJL** [comment]
Avec la 5.3.1, tout semble ok maintenant pour moi 👍

**Comment by Aohzan** [comment]
Conso du jour c'est normal, il faut s'appuyer sur le total pour le dashboard energy
