### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by geoninjaone** [Aohzan/ecodevices#6]
Hello, after installation in HA, i use menu integration, but when i complete all folder, when i submit i receive message to Failed to connect. thank a lot for your help.

**Comment by Aohzan** [comment]
Hello, can you try with the new version : https://github.com/Aohzan/ecodevices/releases/tag/2.0.0

**Comment by geoninjaone** [comment]
hello, same issue.... I use ECODEVICE RT2, it is compatible ?

**Comment by Aohzan** [comment]
(it's already you the first post :grin: )
No it's not compatible, it's not the same API

**Comment by geoninjaone** [comment]
thank a lot. I dream for RT2 in HA ready to use !

**Comment by Aohzan** [comment]
Here : https://github.com/pcourbin/ha-ecodevices-rt2

**Comment by geoninjaone** [comment]
ohhhh big thank you, you make my day !
