### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by BmdOnline** [Aohzan/ecodevices#7]
Hi,
Using hass 2021.3.x, and now 2021.4.x, I have this warning :
`WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'ecodevices'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ecodevices'`.

This will break ecodevice usage in future versions.
Thanks.

**Comment by Aohzan** [comment]
fixed: https://github.com/Aohzan/ecodevices/releases/tag/2.0.0
